using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LINQ_Practice.Models;

namespace LINQ_Practice.Controllers
{
    public class LINQautoGeneratedController : Controller
    {
        private readonly DB2023_LINQContext _context;

        public LINQautoGeneratedController(DB2023_LINQContext context)
        {
            _context = context;
        }

        // GET: LINQautoGenerated
        public async Task<IActionResult> Index()
        {
            var dB2023_LINQContext = _context.TblEmployees.Include(t => t.DepartmentNavigation);
            return View(await dB2023_LINQContext.ToListAsync());
        }

        // GET: LINQautoGenerated/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblEmployees == null)
            {
                return NotFound();
            }

            var tblEmployee = await _context.TblEmployees
                .Include(t => t.DepartmentNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblEmployee == null)
            {
                return NotFound();
            }

            return View(tblEmployee);
        }

        // GET: LINQautoGenerated/Create
        public IActionResult Create()
        {
            ViewData["Department"] = new SelectList(_context.TblDepartments, "Id", "Id");
            return View();
        }

        // POST: LINQautoGenerated/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Age,Salary,Department,Gender")] TblEmployee tblEmployee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblEmployee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Department"] = new SelectList(_context.TblDepartments, "Id", "Id", tblEmployee.Department);
            return View(tblEmployee);
        }

        // GET: LINQautoGenerated/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblEmployees == null)
            {
                return NotFound();
            }

            var tblEmployee = await _context.TblEmployees.FindAsync(id);
            if (tblEmployee == null)
            {
                return NotFound();
            }
            ViewData["Department"] = new SelectList(_context.TblDepartments, "Id", "Id", tblEmployee.Department);
            return View(tblEmployee);
        }

        // POST: LINQautoGenerated/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Age,Salary,Department,Gender")] TblEmployee tblEmployee)
        {
            if (id != tblEmployee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblEmployee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblEmployeeExists(tblEmployee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Department"] = new SelectList(_context.TblDepartments, "Id", "Id", tblEmployee.Department);
            return View(tblEmployee);
        }

        // GET: LINQautoGenerated/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblEmployees == null)
            {
                return NotFound();
            }

            var tblEmployee = await _context.TblEmployees
                .Include(t => t.DepartmentNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblEmployee == null)
            {
                return NotFound();
            }

            return View(tblEmployee);
        }

        // POST: LINQautoGenerated/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblEmployees == null)
            {
                return Problem("Entity set 'DB2023_LINQContext.TblEmployees'  is null.");
            }
            var tblEmployee = await _context.TblEmployees.FindAsync(id);
            if (tblEmployee != null)
            {
                _context.TblEmployees.Remove(tblEmployee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblEmployeeExists(int id)
        {
          return _context.TblEmployees.Any(e => e.Id == id);
        }
    }
}
